name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build . --file pw/pw-jwt-oauth/server/src/main/docker/Dockerfile --tag pw-jwt-oauth:$(date +%s)